DECLARE @DISPNAME nvarchar(23);
DECLARE @LIFESPANACTION int;
DECLARE @WSQL nvarchar(max);
DECLARE @WSQLJET nvarchar(max);
DECLARE @WSQLSQL nvarchar(max);

SET @DISPNAME = 'SessionLatency';
SET @LIFESPANACTION = 1;
SET @WSQL = 
'SELECT
	SASESSION.WGUID
	,GETUTCDATE() AS VWTIME
	,SAGUIDS.WSERVER
	,SASTRUSER.STRVALUE AS USER_NAME
	,SASTRCLADDR.STRVALUE AS CLIENT_IP
	,''ICA'' AS PROTOCOL
	,DATEADD(n, CEILING(DATEDIFF(n, 0, SAICA.WTIME) / 10) * 10,  0) AS WTIME
	,SAICA.LAT_LAST_REC AS LATENCY
FROM
	(((SAICA
INNER JOIN
	SAGUIDS
ON
	SAICA.WGUID = SAGUIDS.WGUID)
INNER JOIN
	SASESSION
ON
	SAICA.SESSIONNUM = SASESSION.SESSIONNUM)
INNER JOIN
	SASTRUSER
ON
	SASESSION.ACCOUNT_ID = SASTRUSER.STRINGID)
INNER JOIN
	SASTRCLADDR
ON
	SASESSION.CL_ADDR_ID = SASTRCLADDR.STRINGID
WHERE
	WTYPE = 1
	AND WTIME > <LASTREFRESHTIME>
UNION ALL
SELECT
	SASESSION.WGUID
	,GETUTCDATE() AS VWTIME
	,SAGUIDS.WSERVER
	,SASTRUSER.STRVALUE AS USER_NAME
	,SASTRCLADDR.STRVALUE AS CLIENT_IP
	,''PCOIP'' AS PROTOCOL
	,DATEADD(n, CEILING(DATEDIFF(n, 0, SAPCOIP.WTIME) / 10) * 10,  0) AS WTIME
	,SAPCOIP.ROUND_TRIP_LATENCY_MS AS LATENCY
FROM
	(((SAPCOIP
INNER JOIN
	SAGUIDS
ON
	SAPCOIP.WGUID = SAGUIDS.WGUID)
INNER JOIN
	SASESSION
ON
	SAPCOIP.SESSIONNUM = SASESSION.SESSIONNUM)
INNER JOIN
	SASTRUSER
ON
	SASESSION.ACCOUNT_ID = SASTRUSER.STRINGID)
INNER JOIN
	SASTRCLADDR
ON
	SASESSION.CL_ADDR_ID = SASTRCLADDR.STRINGID
WHERE
	WTYPE = 1
	AND WTIME > <LASTREFRESHTIME>
UNION ALL
SELECT
	SASESSION.WGUID
	,GETUTCDATE() AS VWTIME
	,SAGUIDS.WSERVER
	,SASTRUSER.STRVALUE AS USER_NAME
	,SASTRCLADDR.STRVALUE AS CLIENT_IP
	,''BLAST'' AS PROTOCOL
	,DATEADD(n, CEILING(DATEDIFF(n, 0, SABLAST.WTIME) / 10) * 10,  0) AS WTIME
	,SABLAST.VNC_EST_RTT AS LATENCY
FROM
	(((SABLAST
INNER JOIN
	SAGUIDS
ON
	SABLAST.WGUID = SAGUIDS.WGUID)
INNER JOIN
	SASESSION
ON
	SABLAST.SESSIONNUM = SASESSION.SESSIONNUM)
INNER JOIN
	SASTRUSER
ON
	SASESSION.ACCOUNT_ID = SASTRUSER.STRINGID)
INNER JOIN
	SASTRCLADDR
ON
	SASESSION.CL_ADDR_ID = SASTRCLADDR.STRINGID
WHERE
	WTYPE = 1
	AND WTIME > <LASTREFRESHTIME>
UNION ALL
SELECT
	SASESSION.WGUID
	,GETUTCDATE() AS VWTIME
	,SAGUIDS.WSERVER
	,SASTRUSER.STRVALUE AS USER_NAME
	,SASTRCLADDR.STRVALUE AS CLIENT_IP
	,''BLAST2'' AS PROTOCOL
	,DATEADD(n, CEILING(DATEDIFF(n, 0, SABLAST2.WTIME) / 10) * 10,  0) AS WTIME
	,SABLAST2.SESS_RTT AS LATENCY
FROM
	(((SABLAST2
INNER JOIN
	SAGUIDS
ON
	SABLAST2.WGUID = SAGUIDS.WGUID)
INNER JOIN
	SASESSION
ON
	SABLAST2.SESSIONNUM = SASESSION.SESSIONNUM)
INNER JOIN
	SASTRUSER
ON
	SASESSION.ACCOUNT_ID = SASTRUSER.STRINGID)
INNER JOIN
	SASTRCLADDR
ON
	SASESSION.CL_ADDR_ID = SASTRCLADDR.STRINGID
WHERE
	WTYPE = 1
	AND WTIME > <LASTREFRESHTIME>
UNION ALL
SELECT
	SASESSION.WGUID
	,GETUTCDATE() AS VWTIME
	,SAGUIDS.WSERVER
	,SASTRUSER.STRVALUE AS USER_NAME
	,SASTRCLADDR.STRVALUE AS CLIENT_IP
	,''RDP'' AS PROTOCOL
	,DATEADD(n, CEILING(DATEDIFF(n, 0, SAREMOTEFX.WTIME) / 10) * 10,  0) AS WTIME
	,SAREMOTEFX.CUR_UDP_RTT AS LATENCY
FROM
	(((SAREMOTEFX
INNER JOIN
	SAGUIDS
ON
	SAREMOTEFX.WGUID = SAGUIDS.WGUID)
INNER JOIN
	SASESSION
ON
	SAREMOTEFX.SESSIONNUM = SASESSION.SESSIONNUM)
INNER JOIN
	SASTRUSER
ON
	SASESSION.ACCOUNT_ID = SASTRUSER.STRINGID)
INNER JOIN
	SASTRCLADDR
ON
	SASESSION.CL_ADDR_ID = SASTRCLADDR.STRINGID
WHERE
	WTYPE = 1
	AND WTIME > <LASTREFRESHTIME>
';
 SET @WSQLJET = '';
 SET @WSQLSQL = '';


IF (SELECT COUNT(*) FROM SAVIEWS WHERE DISPNAME = @DISPNAME) = 0
BEGIN
	INSERT INTO SAVIEWS
           (VIEWID
           ,DISPNAME
           ,WDESC
           ,WTABLE
           ,WFLAGS
           ,WTYPE
           ,LASTTIME
           ,LIFESPAN
           ,LIFESPANTYPE
           ,LIFESPANACTION
           ,REFRESHTYPE
           ,REFRESHACTION
           ,REFRESH
           ,OVERDUEDAYS
           ,TIMEWINDOW
           ,WSQLGUIDS
           ,WSQL
           ,WSQLJET
           ,WSQLSQL
           ,WSQLORACLE)
     VALUES
           (CASE WHEN (SELECT MAX(VIEWID) FROM SAVIEWS) < 1000000 THEN 1000000 ELSE (SELECT MAX(VIEWID) FROM SAVIEWS) + 1 END
           ,@DISPNAME
           ,''
           ,'VU' + @DISPNAME
           ,64
           ,0
           ,'1899-12-30 00:00:00.000'
           ,30
           ,3
           ,@LIFESPANACTION
           ,0
           ,0
           ,1
           ,0
           ,'24x7'
           ,'SELECT WGUID FROM SAGUIDS'
           ,@WSQL
           ,@WSQLJET
           ,@WSQLSQL
           ,'');
        SELECT
               @DISPNAME + N'を追加しました。' AS MSG
END ELSE BEGIN
	IF (SELECT COUNT(*) FROM SAVIEWS WHERE DISPNAME = @DISPNAME AND LIFESPANACTION = @LIFESPANACTION AND WSQL = @WSQL AND WSQLJET = @WSQLJET AND WSQLSQL = @WSQLSQL) = 0
	BEGIN
		UPDATE SAVIEWS
              SET
                     LIFESPANACTION = @LIFESPANACTION
                     ,WSQL = @WSQL
                     ,WSQLJET = @WSQLJET
                     ,WSQLSQL = @WSQLSQL
              WHERE
                     DISPNAME = @DISPNAME;
              SELECT
				   @DISPNAME + N'を更新しました。' AS MSG
	END ELSE BEGIN
        SELECT
               @DISPNAME + N'は既に存在します。' AS MSG
   END
END
